{% set name = "desktop3" %}
{% set version = "0.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  sha256: 37e8bfbfbd0ce97471fc48bf5b9ddb2459b7e5f2756b2f5e682831f365723615

build:
  number: 1001
  skip: true  # [py2k]
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - desktop

about:
  home: https://github.com/eight04/pyDesktop3
  license: GNU Lesser General Public v3 or later (LGPLv3+)
  license_family: LGPL
  license_file: 'docs/COPYING.txt'
  summary: 'Simple desktop integration for Python.'
  description: |
    The desktop package provides desktop environment detection and
    resource opening support for a selection of common and standardised
    desktop environments.
  dev_url: https://github.com/eight04/pyDesktop3

extra:
  recipe-maintainers:
    - eight04
    - tadeu
    - nicoddemus
