{% set name = "desktop3" %}
{% set version = "0.5.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a82a49352dac14faa77e31fef8b0773667a2ce83deafc44abc1484d19ea44f6b

build:
  noarch: python
  number: 7
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - desktop

about:
  home: https://github.com/eight04/pyDesktop3
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: docs/COPYING.txt
  summary: Simple desktop integration for Python.
  description: |
    The desktop package provides desktop environment detection and
    resource opening support for a selection of common and standardised
    desktop environments.
  dev_url: https://github.com/eight04/pyDesktop3

extra:
  recipe-maintainers:
    - eight04
    - tadeu
    - nicoddemus
