travis:
  secure:
    BINSTAR_TOKEN: sk5yY10q/LY8534ivd1ICbE6LvZzpch6eUq4jWy7HIGjYUqHo0N4l6sSPpANUg4f+W7sGSQBtg9kL7v5W2m1xlrseI90DEIreocA4v37Dkn+7tSreXq2gikh9lLnRTUMIqDpJiJIRwcwRS9DZi0mvY2ajAj2RaB/tTDAWYNmJETUKe4/h1sgr5EqvQ/WVmnD7KzaFTq0+c840sGVyS+K2SSoZNwE4rp+IDAf2hhZjNgzcjf7/swb6aH5B3oPLDt0KVAl5ooBsK/EcyWu8OgQxpc8Mz+FUbXbfmmnGff3cO+qHw+IYmy9VKg6/1aHJzFudajgEwfZygkilDGyn79VrIKe9nh/Up32a9jzSEECcwOQigIh9wirnQmV7JS9zvrIu6PUGITnQBOoB1OxAdu1/dYOwJXBBPLLUzpX/G7oizmPEl3y3ldwq+dXfadkkAP8qoAsAufBUq4Fa0hatXT2FAlLFIBLGs3RppBDlpBlendbyfDDWuXjTw1Av0NpIbW72OaCynpx9dcbpEO1UvDnuD6SXOCY6rGT4g/Zg6Nl7LvHW1VzMZeVwZCltR6d5/gb36bAjz/SpkrASGWK6O4/uluqQul9282HLAjLvzDFwZ2ACO5vY+nxlU2/aossNOCaZ9VGGWyj8Hc/yRqm7bJajdXZgqn/GVOdcpWWYfYym3o=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
