travis:
  secure:
    BINSTAR_TOKEN: nrHVyPixj2j1mjmm4Q+Jmzx/cVo+eHko8Xt2z/MDt0eyb2hmDwiqDVFoTALm0S4+PW2lb4GNE9uICvbacgbvUqxLtK8OxZHFoeX+fdc+SlIH5b+YBitx5P2CT6JEXsIixjRgohUEpvSc1tC1T7yBKIGp06X+sFgwfs6HL6k4BzbEN0besWcV6HnqeK7w2rJY5Go6MK+6YBb490pijStCakTh8eMpWUTGsHgDKxMOwvJadtYAPzmAXAfn4FH3MrElJ2uY+qjIFgZgAT87LacYckAJtmSx49C6TeALnQnnqHNENVVTZ9XHyhvcFWvY8R4p7dgd+1kpuIkKGEot/eoy76cSzbhK0fA3x/liZDuHGcNBK4XDLx0vjOciQ5+a8OpWGfjwpuE93Cw6CQ3GJvCX+h1MlvfRar/xO7Vm4JynWtWHtsIAp4jNL08dYeMknNQeVdDJ6GjCg0xrLFzri8ctWHar5NPIzeWw5dm551RNgz61zkVVDPe5XppOBmFasudOtKNvnobPT37V+J7u0hVyvUv/PWE7U5KSoukTVAxiE1D8xwRIUamR6RY7MhLccZ/pLtpZ07lqhA64LW5uvglLD0Sabqd1aNcMKt7rrlHIuKHVzx6YDmSgqkzVf383Sq1nlVFpl30e2Bm2nCsPTdOk16G7jeeKEN18WB3vXTItmWo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
